# This is a basic workflow to help you get started with Actions

name: AutoFormatter

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  format:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        id: set-args
        with:
          script: |
            if (context.ref.startsWith("refs/pull/")){
              return "--set-exit-if-changed --skip-sorting-imports"
            }
            return "-r --skip-sorting-imports";
          result-encoding: string
      
      - name: Google Java Format
        # You may pin to the exact commit or the version.
        # uses: axel-op/googlejavaformat-action@5045c8c244a22eb6a28eeb6050cc2baebd75c5f2
        uses: axel-op/googlejavaformat-action@v3.4.0
        with:
          version: 1.6
          skipCommit: ${{ startsWith(github.ref, 'refs/pull/') }}
          args: ${{steps.set-args.outputs.result}}
          
